# Generated by Django 5.1.4 on 2025-01-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqmodel',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
