# Generated by Django 5.1.4 on 2025-01-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_delete_customusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUsers',
        ),
    ]
