# Generated by Django 5.1.4 on 2025-01-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
